kind: Service
apiVersion: v1
metadata:
  name: django-service
  namespace: default
spec:
  selector:
    app: django-app
  type:  ClusterIP
  ports:
  - name: django-svr
    protocol: TCP
    port: 8888 
    targetPort: 8000