apiVersion: apps/v1
kind: Deployment
metadata:
  name:  django-app
  namespace: default
  labels:
    name: django
spec:
  selector:
    matchLabels:
      app: django
  replicas: 1
  template:
    metadata:
      labels:
        app: django
    spec:
      initContainers:
      - name: django-init
        image: ghcr.io/nikos-kaparos/django:2f04126-10
        command: ["/bin/sh", "-c", "python manage.py makemigrations && python manage.py migrate"] 
        envFrom:
          - configMapRef:
              name: django-config
        volumeMounts:
          - name: django-storage
            mountPath: /storage      
      volumes:
        - name: django-storage
          persistentVolumeClaim:
            claimName: django-volume
      containers:
      - name: django
        image: ghcr.io/nikos-kaparos/django:2f04126-10
        resources:
          requests:
            cpu: "100m"
            memory: "100M"
          limits:
            cpu: "500m"
            memory: "300Mi"
       #dont need it only fro example
        env:
        - name: ENV1
          value: test
        - name: DH_HOST
          valueFrom:
            configMapKeyRef:
              name: django-config
              key: SECRET_KEY
        #this is what we need
        envFrom:
          - configMapRef:
              name: django-config
        ports:
        - containerPort: 8000
          name:  django
        volumeMounts:
          - name: django-storage
            mountPath: /storage
      restartPolicy: Always
      imagePullSecrets:
        - name: registry-credentials