apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  namespace: default
  labels:
    app: django
spec:
  selector:
    matchLabels:
      app: django
  replicas: 1
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: ghcr.io/nikos-kaparos/django:2f04126-10
        resources:
          limits:
            memory: "300Mi"
            cpu: "500m"
      env:
        - name:  ENV1
          value: test
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: django-onfig
              key: SECRET_KEY
      envFrom:
        - configMapKeyRef:
            name: django-config
      ports:
        - containerPort: 8000
          name: django
    restartPolicy: Alwyas